name: Scheduled Cron Job

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  run-app:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6.2
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Build and run containers
        run: docker-compose up --build -d

      - name: Wait for services to be ready
        run: sleep 30

      - name: Execute the application
        run: docker-compose exec app ./search-app

      - name: Teardown
        if: always()
        run: docker-compose down